name: CI/CD

on:
  push:
    branches: [ '**' ]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Stylelint
        run: npm run css
  deploy:
    needs: [ linters ]
    runs-on: ubuntu-latest
    steps:
      - name: download service
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "."
          target: "/home/ubuntu/front-next"

      - name: build service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd front-next && npm ci && npm run start
