name: linter

on:
  push:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Stylelint
        run: npm run css
